### ISSUE TITLE
При установке через композер ошибка.

### ISSUE THREAD

**Issue by asyou99** [PopcornPHP/sdk-fondy#1]
Пробовал задавать разные версии пакета ничего не помогло. 
[InvalidArgumentException]
  Could not find package popcornphp/sdk-fondy at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by OleksandrWebLab** [comment]
Изменил minimum stability на stable, добавил релиз. Сейчас должно работать

**Comment by asyou99** [comment]
в ридми поменяйте composer require popcornphp/sdk-fondy на composer require popcornphp/fondy т.к. у вас имя пакета в композере записано как  "name": "popcornphp/fondy", из за этого  и трабл был я на почте в повторнм письме отписался.

**Comment by OleksandrWebLab** [comment]
Спасибо, исправил

**Comment by PopcornPHP** [comment]
спасибо, исправил
